### ISSUE TITLE
Switch PDF‐processing to an internal FastAPI microservice 🚀

### ISSUE THREAD

**Issue by aliamerj** [Dcup-dev/dcup#69]
### 🐛 Background
Our current approach spawns a Python CLI from inside the Next.js/Node Docker container on Alpine. In production (Render) this leads to intermittent `EPIPE` hangs, venv‐build failures on Alpine, SSL/cert issues, and opaque child‐process errors.

### 💡 Proposed Solution
Replace the in‐process Python CLI with a **dedicated FastAPI service** running on `localhost:9000`:

- **Local (dev)**: Run via `docker-compose.yml` as an internal-only service (`pdfsvc`), no public port mapping.
- **Production (Render)**: Deploy both the Next.js app and FastAPI service using Render Blueprints (`render.yaml`), in the same private network, with the FastAPI container **not** exposed to the public internet.

Node will simply `POST` PDF buffers (or links) to `http://pdfsvc:9000/extract` and ingest the JSON response.

### 🔨 Implementation Steps
1. **python-service/**
   - `app.py`: FastAPI endpoint `/extract` that accepts `UploadFile` and returns parsed pages/tables using `pdfplumber`.
   - `Dockerfile`: slim‐Python image with `uvicorn`, `pdfplumber`, etc.
2. **docker-compose.yml** (dev)
   ```yaml
   version: '3.8'
   services:
     web:
       build: .
       ports: ['8080:8080']
       depends_on: ['pdfsvc']
     pdfsvc:
       build: ./python-service
       # no external ports—internal only

3. **render.yaml** (prod)

```yaml
services:
  - type: web
    name: dcup-web
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    plan: free
  - type: web
    name: dcup-pdfsvc
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 9000
    internal: true
    plan: free
```
4. **Node client update**
Swap out the child‐process wrapper for an HTTP call to http://pdfsvc:9000/extract.

##### ✅ Benefits
- Reliability: no more Alpine‐venv build/EPIPE issues
- Security: parsing service runs on an internal network only
- Maintainability: clear separation of concerns, easier to debug/log
